### ISSUE TITLE
ERROR during file cleanup on Apple Silicon

### ISSUE THREAD

**Issue by jaimemarijke** [NREL/resstock#1035]
After moving to an M2 mac, I started seeing this error during the xml validation file cleanup step: 

```
[17:15:34.200075 ERROR] No such file or directory @ apply2files - /var/folders/5g/6ydq2ctj7px9fkq309znm_fr0000gn/T/xmlvalidation-1677633333-0
:/ruby/2.7.0/fileutils.rb:1466:in `unlink'
:/ruby/2.7.0/fileutils.rb:1466:in `block in remove_file'
:/ruby/2.7.0/fileutils.rb:1471:in `platform_support'
:/ruby/2.7.0/fileutils.rb:1465:in `remove_file'
:/ruby/2.7.0/fileutils.rb:1454:in `remove'
:/ruby/2.7.0/fileutils.rb:780:in `block in remove_entry'
:/ruby/2.7.0/fileutils.rb:1509:in `postorder_traverse'
:/ruby/2.7.0/fileutils.rb:778:in `remove_entry'
:/ruby/2.7.0/fileutils.rb:630:in `block in rm_r'
:/ruby/2.7.0/fileutils.rb:626:in `each'
:/ruby/2.7.0/fileutils.rb:626:in `rm_r'
/Users/jaime/optionzero/nrgx-energy-modeling/resstock/resources/hpxml-measures/HPXMLtoOpenStudio/resources/xmlvalidator.rb:76:in `cleanup_openstudio_tmp_dir'
/Users/jaime/optionzero/nrgx-energy-modeling/resstock/resources/hpxml-measures/HPXMLtoOpenStudio/resources/xmlvalidator.rb:65:in `validate_against_schematron'
/Users/jaime/optionzero/nrgx-energy-modeling/resstock/resources/hpxml-measures/HPXMLtoOpenStudio/resources/hpxml.rb:414:in `initialize'
/Users/jaime/optionzero/nrgx-energy-modeling/resstock/resources/hpxml-measures/HPXMLtoOpenStudio/measure.rb:118:in `new'
/Users/jaime/optionzero/nrgx-energy-modeling/resstock/resources/hpxml-measures/HPXMLtoOpenStudio/measure.rb:118:in `run'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/measure.rb:517:in `apply_measure'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/measure.rb:114:in `block in apply_measures'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/measure.rb:67:in `each_index'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/measure.rb:67:in `apply_measures'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/jobs/run_os_measures.rb:70:in `perform'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/run.rb:291:in `step'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/run.rb:233:in `run'
:/openstudio_cli.rb:1184:in `execute'
:/openstudio_cli.rb:814:in `execute'
:/openstudio_cli.rb:1983:in `<main>'
eval:188:in `eval'
eval:188:in `require_embedded_absolute'
eval:173:in `block in require_embedded'
eval:167:in `each'
eval:167:in `require_embedded'
eval:126:in `require'
eval:3:in `<main>'
```

**Chip:** Apple Silicon M2
**OS:** 13.2.1 (22D68)
**Ruby version:** 2.7.2p137 (2020-10-01 revision 5445e04352) [arm64-darwin22]
**Bundle version:** 2.1.4

**Comment by shorowit** [comment]
Addressed by https://github.com/NREL/resstock/commit/8a41cd2e4289441e0e52785794e425f682cc1ea0.
