### ISSUE TITLE
Unable to run test project

### ISSUE THREAD

**Issue by sudeepy** [NREL/resstock#719]
Hi, I'm just getting starting with ResStock. I've installed OpenStudio and downloaded a recent developer checkout (a4ac4fe). Unfortunately I cannot get the basic baseline test project to run (per https://resstock.readthedocs.io/en/latest/tutorial/run_project.html)

At first I get the following error:
> sudeepy@sudeepy-m1-mbp resstock-develop-a4ac4fe % openstudio workflow/run_analysis.rb -y project_testing/testing_baseline.yml
> :/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/version.rb:4: warning: already initialized constant JSON::VERSION
> :/ruby/2.2.0/json/version.rb:3: warning: previous definition of VERSION was here
> :/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/version.rb:5: warning: already initialized constant JSON::VERSION_ARRAY
> :/ruby/2.2.0/json/version.rb:4: warning: previous definition of VERSION_ARRAY was here
> :/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/version.rb:6: warning: already initialized constant JSON::VERSION_MAJOR
> :/ruby/2.2.0/json/version.rb:5: warning: previous definition of VERSION_MAJOR was here
> :/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/version.rb:7: warning: already initialized constant JSON::VERSION_MINOR
> :/ruby/2.2.0/json/version.rb:6: warning: previous definition of VERSION_MINOR was here
> :/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/version.rb:8: warning: already initialized constant JSON::VERSION_BUILD
> :/ruby/2.2.0/json/version.rb:7: warning: previous definition of VERSION_BUILD was here
> :/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/common.rb:100: warning: already initialized constant JSON::NaN
> :/ruby/2.2.0/json/common.rb:99: warning: previous definition of NaN was here
> :/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/common.rb:102: warning: already initialized constant JSON::Infinity
> :/ruby/2.2.0/json/common.rb:101: warning: previous definition of Infinity was here
> :/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/common.rb:104: warning: already initialized constant JSON::MinusInfinity
> :/ruby/2.2.0/json/common.rb:103: warning: previous definition of MinusInfinity was here
> :/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/common.rb:129: warning: already initialized constant JSON::UnparserError
> :/ruby/2.2.0/json/common.rb:128: warning: previous definition of UnparserError was here
> Ignoring executable-hooks-1.6.1 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.6.1
> Ignoring ffi-1.9.25 because its extensions are not built.  Try: gem pristine ffi --version 1.9.25
> Ignoring gem-wrappers-1.4.0 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.4.0
> Ignoring json-2.5.1 because its extensions are not built.  Try: gem pristine json --version 2.5.1
> Ignoring executable-hooks-1.6.1 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.6.1
> Ignoring ffi-1.9.25 because its extensions are not built.  Try: gem pristine ffi --version 1.9.25
> Ignoring gem-wrappers-1.4.0 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.4.0
> Ignoring json-2.5.1 because its extensions are not built.  Try: gem pristine json --version 2.5.1
> YML: project_testing/testing_baseline.yml
> 
> Error: uninitialized constant UrlResolver::OpenSSL
> Backtrace:
> 	eval:289:in `const_missing'
> 	/Users/sudeepy/mvts/retrofit_plans/resstock-develop-a4ac4fe/resources/util.rb:26:in `fetch'
> 	/Users/sudeepy/mvts/retrofit_plans/resstock-develop-a4ac4fe/workflow/run_analysis.rb:117:in `run_workflow'
> 	/Users/sudeepy/mvts/retrofit_plans/resstock-develop-a4ac4fe/workflow/run_analysis.rb:261:in `<top (required)>'
> 	eval:107:in `require'
> 	eval:107:in `require'
> 	:/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
> 	:/openstudio_cli.rb:1511:in `execute'
> 	:/openstudio_cli.rb:763:in `execute'
> 	:/openstudio_cli.rb:1746:in `<main>'
> 	eval:116:in `eval'
> 	eval:116:in `require_embedded_absolute'
> 	eval:101:in `block in require'
> 	eval:95:in `each'
> 	eval:95:in `require'
> 	eval:3:in `<main>'
> Exception: uninitialized constant UrlResolver::OpenSSL
> <main>: unexpected return

I then tried adding `require 'openssl'` to the top of `resources/util.rb` but then get the following:
> sudeepy@sudeepy-m1-mbp resstock-develop-a4ac4fe % openstudio workflow/run_analysis.rb -y project_testing/testing_baseline.yml
> :/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/version.rb:4: warning: already initialized constant JSON::VERSION
> :/ruby/2.2.0/json/version.rb:3: warning: previous definition of VERSION was here
> :/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/version.rb:5: warning: already initialized constant JSON::VERSION_ARRAY
> :/ruby/2.2.0/json/version.rb:4: warning: previous definition of VERSION_ARRAY was here
> :/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/version.rb:6: warning: already initialized constant JSON::VERSION_MAJOR
> :/ruby/2.2.0/json/version.rb:5: warning: previous definition of VERSION_MAJOR was here
> :/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/version.rb:7: warning: already initialized constant JSON::VERSION_MINOR
> :/ruby/2.2.0/json/version.rb:6: warning: previous definition of VERSION_MINOR was here
> :/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/version.rb:8: warning: already initialized constant JSON::VERSION_BUILD
> :/ruby/2.2.0/json/version.rb:7: warning: previous definition of VERSION_BUILD was here
> :/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/common.rb:100: warning: already initialized constant JSON::NaN
> :/ruby/2.2.0/json/common.rb:99: warning: previous definition of NaN was here
> :/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/common.rb:102: warning: already initialized constant JSON::Infinity
> :/ruby/2.2.0/json/common.rb:101: warning: previous definition of Infinity was here
> :/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/common.rb:104: warning: already initialized constant JSON::MinusInfinity
> :/ruby/2.2.0/json/common.rb:103: warning: previous definition of MinusInfinity was here
> :/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/common.rb:129: warning: already initialized constant JSON::UnparserError
> :/ruby/2.2.0/json/common.rb:128: warning: previous definition of UnparserError was here
> Ignoring executable-hooks-1.6.1 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.6.1
> Ignoring ffi-1.9.25 because its extensions are not built.  Try: gem pristine ffi --version 1.9.25
> Ignoring gem-wrappers-1.4.0 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.4.0
> Ignoring json-2.5.1 because its extensions are not built.  Try: gem pristine json --version 2.5.1
> Ignoring executable-hooks-1.6.1 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.6.1
> Ignoring ffi-1.9.25 because its extensions are not built.  Try: gem pristine ffi --version 1.9.25
> Ignoring gem-wrappers-1.4.0 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.4.0
> Ignoring json-2.5.1 because its extensions are not built.  Try: gem pristine json --version 2.5.1
> 
> Error: cannot load such file -- openssl
> Backtrace:
> 	eval:107:in `require'
> 	eval:107:in `require'
> 	:/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
> 	/Users/sudeepy/mvts/retrofit_plans/resstock-develop-a4ac4fe/resources/util.rb:1:in `<top (required)>'
> 	eval:107:in `require'
> 	eval:107:in `require'
> 	:/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
> 	eval:126:in `require_relative'
> 	/Users/sudeepy/mvts/retrofit_plans/resstock-develop-a4ac4fe/workflow/run_analysis.rb:8:in `<top (required)>'
> 	eval:107:in `require'
> 	eval:107:in `require'
> 	:/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
> 	:/openstudio_cli.rb:1511:in `execute'
> 	:/openstudio_cli.rb:763:in `execute'
> 	:/openstudio_cli.rb:1746:in `<main>'
> 	eval:116:in `eval'
> 	eval:116:in `require_embedded_absolute'
> 	eval:101:in `block in require'
> 	eval:95:in `each'
> 	eval:95:in `require'
> 	eval:3:in `<main>'
> Exception: cannot load such file -- openssl
> <main>: unexpected return

At first I thought this was an issue with my local ruby installation. After some digging, it looks like OpenStudio is loading its own bundled ruby 2.2.0* and not what's installed on my computer. I'm not very familiar with ruby configuration, but I cannot get OpenStudio's ruby to load openssl and actually run the job.

Any help would be greatly appreciated!

\* for those curious, the bundled ruby is found at `/Applications/OpenStudio-2.9.0/ParametricAnalysisTool.app/Contents/Resources/ruby/`.

**Comment by joseph-robertson** [comment]
That's a good point. It's somewhat buried in the code (i.e., https://github.com/NREL/resstock/blob/develop/.github/workflows/config.yml#L14) but intentionally left out of the docs so that we don't have to update it for every version change. I'll find a place to make it more visible.

**Comment by sudeepy** [comment]
Thanks; I appreciate it.
