### ISSUE TITLE
'osb_thick_in' not provided for measure 'ResidentialConstructionsWallsWoodStud'

### ISSUE THREAD

**Issue by nmerket** [NREL/resstock#826]
I'm getting a few simulation failures when I run national_upgrades.yml on Eagle with 10 datapoints. Here's the [buildstock.csv](https://github.com/NREL/resstock/files/8028357/buildstock.csv). 

The error is:

```
[16:43:15.478194 ERROR] Required argument 'osb_thick_in' not provided for measure 'ResidentialConstructionsWallsWoodStud'.
[16:43:15.478330 ERROR] Required argument 'osb_thick_in' not provided for measure 'ResidentialConstructionsWallsWoodStud'.
```

```
/lib/resources/meta_measure.rb:238:in `register_error'
        /lib/resources/meta_measure.rb:119:in `block in validate_measure_args'
        /lib/resources/meta_measure.rb:115:in `each'
        /lib/resources/meta_measure.rb:115:in `validate_measure_args'
        /lib/resources/meta_measure.rb:165:in `get_argument_map'
        /lib/resources/meta_measure.rb:69:in `block (2 levels) in apply_measures'
        /lib/resources/meta_measure.rb:68:in `each'
        /lib/resources/meta_measure.rb:68:in `block in apply_measures'
        /lib/resources/meta_measure.rb:63:in `each'
        /lib/resources/meta_measure.rb:63:in `apply_measures'
        /measures/ApplyUpgrade/measure.rb:314:in `run'
        :/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/measure.rb:517:in `apply_measure'
        :/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/measure.rb:114:in `block in apply_measures'
        :/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/measure.rb:67:in `each_index'
        :/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/measure.rb:67:in `apply_measures'
        :/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/jobs/run_os_measures.rb:70:in `perform'
        :/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/run.rb:291:in `step'
        :/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/run.rb:233:in `run'
        :/openstudio_cli.rb:1067:in `execute'
        :/openstudio_cli.rb:803:in `execute'
        :/openstudio_cli.rb:1855:in `<main>'
        eval:186:in `eval'
        eval:186:in `require_embedded_absolute'
        eval:171:in `block in require_embedded'
        eval:165:in `each'
        eval:165:in `require_embedded'
        eval:124:in `require'
        eval:3:in `<main>'
```

A couple of the buildings that failed:

| Upgrade | Building ID|
| --- | --- |
| 2 | 4 |
| 2 | 8 |
| 2 | 10 |
| 9 | 10 |

- resstock sha: 17a9349fc
- buildstockbatch sha: 3523e09
- Compute Environment: Eagle

**Comment by joseph-robertson** [comment]
@nmerket I'm assuming you're not using https://github.com/NREL/resstock/blob/develop/project_national/national_upgrades.yml (because n=10 instead of n=1)? Can you attach your yml?

**Comment by nmerket** [comment]
Basically the only substantial thing I changed was the n_datapoints. Here's my yaml:

[national_upgrades.yml.txt](https://github.com/NREL/resstock/files/8028428/national_upgrades.yml.txt)
